# RunPod Template Configuration
# Pro LoRA Style Transfer aplikaci

apiVersion: runpod.io/v1
kind: Template
metadata:
  name: lora-style-transfer
  description: "AI-powered LoRA Style Transfer with Stable Diffusion"
  version: "1.0.0"
  tags:
    - ai
    - stable-diffusion
    - lora
    - style-transfer
    - gpu

spec:
  # Container konfigurace
  container:
    image: "your-registry/lora-style-transfer:latest"
    ports:
      - containerPort: 8000
        name: api
        protocol: TCP
      - containerPort: 3000
        name: frontend
        protocol: TCP
    
    # Environment variables
    env:
      - name: CUDA_VISIBLE_DEVICES
        value: "0"
      - name: PYTORCH_CUDA_ALLOC_CONF
        value: "max_split_size_mb:512"
      - name: OMP_NUM_THREADS
        value: "4"
      - name: NEXT_PUBLIC_API_URL
        value: "http://localhost:8000"
    
    # Resource requirements
    resources:
      requests:
        memory: "8Gi"
        nvidia.com/gpu: 1
      limits:
        memory: "16Gi"
        nvidia.com/gpu: 1
    
    # Volume mounts
    volumeMounts:
      - name: models-storage
        mountPath: /data/models
      - name: loras-storage
        mountPath: /data/loras
      - name: temp-storage
        mountPath: /tmp/processing
    
    # Health checks
    livenessProbe:
      httpGet:
        path: /api/health
        port: 8000
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 3
    
    readinessProbe:
      httpGet:
        path: /api/health
        port: 8000
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3

  # Volume konfigurace
  volumes:
    - name: models-storage
      persistentVolumeClaim:
        claimName: models-pvc
    - name: loras-storage
      persistentVolumeClaim:
        claimName: loras-pvc
    - name: temp-storage
      emptyDir:
        sizeLimit: 10Gi

  # GPU requirements
  nodeSelector:
    accelerator: nvidia-tesla-v100  # nebo nvidia-rtx-4090, nvidia-a100
    
  # Startup command
  command: ["/app/docker-entrypoint.sh"]
  args: ["backend"]  # Spustí pouze backend, frontend je volitelný

---
# Persistent Volume Claims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi  # Prostor pro Stable Diffusion modely
  storageClassName: fast-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loras-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi   # Prostor pro LoRA modely
  storageClassName: fast-ssd